machine:
  services:
    - docker

general:
  branches:
    only:
    - master

dependencies:
  override:
    - |
      mkdir -p /home/ubuntu/engineering/build
      docker run -v /home/ubuntu/engineering/:/source jekyll/jekyll:pages jekyll build --source /source --destination /source/build

test:
  override:
    - echo "Nothing to see here"

deployment:
  development:
    branch: master # Should be develop or something like that
    commands: 
      - aws s3 sync ./build/ s3://${S3_ENGINEERING_BUCKET}/ --delete --exclude "circle.yml" 